In [24]:
import numpy as np
import pandas as pd
import math
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier
import imblearn
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline
from sklearn import preprocessing
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold

In [25]:
train=pd.read_csv("pre_processed_train.csv")
test=pd.read_csv("pre_processed_test.csv")

In [26]:
train

,Unnamed: 0,TransactionID,isFraud,TransactionAmt,card1,card2,card3,card5,addr1,dist1,...,M4_M3,M5_F,M5_N,M5_T,M6_F,M6_N,M6_T,M8_F,M8_N,M8_T
0,0,3424175,0,7.000000,5033.0,269.0,150.0,224.0,330.0,2.449490,...,0,0,0,1,1,0,0,0,1,0
1,1,3206179,0,7.612490,4527.0,376.0,150.0,226.0,441.0,5.986395,...,1,0,1,0,1,0,0,0,1,0
2,2,3410455,0,10.768008,2772.0,512.0,150.0,226.0,143.0,3.741657,...,1,0,1,0,0,0,1,1,0,0
3,3,3058578,0,10.000000,14290.0,512.0,150.0,226.0,177.0,5.986395,...,1,0,1,0,0,1,0,0,1,0
4,4,3242131,0,9.746794,12839.0,321.0,150.0,226.0,220.0,2.449490,...,0,1,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442900,442900,3020019,0,5.385165,3277.0,111.0,150.0,226.0,231.0,5.986395,...,0,0,0,1,1,0,0,0,1,0
442901,442901,3546388,0,9.848858,18132.0,567.0,150.0,117.0,272.0,2.828427,...,0,0,0,1,1,0,0,0,1,0
442902,442902,3087445,0,10.000000,6019.0,583.0,150.0,226.0,441.0,5.986395,...,1,0,1,0,0,1,0,0,1,0
442903,442903,3066953,0,5.000000,10737.0,399.0,150.0,118.0,204.0,5.986395,...,1,0,1,0,0,1,0,0,1,0
442904,442904,3505849,0,7.071068,6019.0,583.0,150.0,226.0,264.0,5.986395,...,1,0,1,0,0,1,0,0,1,0

In [27]:
t1=train

In [28]:
ytrain=train["isFraud"]
train.drop(axis = 1, labels = ["isFraud","Unnamed: 0"], inplace = True)

In [29]:
test.drop(axis = 1, labels = ["Unnamed: 0"], inplace = True)

In [30]:
over = SMOTE(sampling_strategy=0.1)
under = RandomUnderSampler(sampling_strategy=0.5)
steps = [('o', over),('u',under)]
pipeline = Pipeline(steps=steps)
train1, ytrain1 = pipeline.fit_resample(train, ytrain)

In [31]:
from sklearn.preprocessing import StandardScaler
scale= StandardScaler()
X_train = scale.fit_transform(train1)
X_test=scale.transform(test)

In [34]:
grid_params={'n_neighbors':[3,11,19],
             'weights': ['distance'],
             'metric': ['manhattan']
}
gs=GridSearchCV(KNeighborsClassifier(),grid_params,verbose=1,cv=3,n_jobs=-1,scoring='roc_auc')
gs=gs.fit(X_train,ytrain1)

Fitting 3 folds for each of 3 candidates, totalling 9 fits

In [35]:
print("Tuned Hyperparameters :", gs.best_params_)
print("Accuracy :",gs.best_score_)

Tuned Hyperparameters : {'metric': 'manhattan', 'n_neighbors': 19, 'weights': 'distance'}
Accuracy : 0.9510355725590736

In [36]:
y_pred1 = gs.predict(X_test)
y_pred1.sum()

6604

In [ ]:
classifier = KNeighborsClassifier(metric='manhattan',n_neighbors=19,weights='distance')
classifier.fit(X_train, ytrain1)
y_pred1 = classifier.predict(X_test)

In [37]:
import csv
with open('knn.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["Id","isFraud"])
    idx=0
    for i in y_pred1:
        writer.writerow([idx,i])
        idx=idx+1

In [39]:
np.linspace(10,100,num=10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])